spring:
  application:
    name: event-sourcing
  # Command side: PostgreSQL
  datasource:
    write:
      jdbc-url: jdbc:postgresql://localhost:5432/order_db
      username: user
      password: pass
      driver-class-name: org.postgresql.Driver
  # Query side: ClickHouse
  clickhouse:
    jdbc-url: jdbc:ch://localhost:8123/default?compress=0
    user: default
    password: "clickhouse"
  # Messaging: kafka
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: event-sourcing-group
      auto-offset-reset: earliest
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.github.learntocode2013.eventsourcing.order.events.DomainEvent
  #Enable JPA for postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
